#!/bin/bash

install_exporter () {

  useradd --no-create-home --shell /bin/false node_exporter
  cp node_exporter /usr/local/bin
  chmod +x /usr/local/bin/node_exporter
  cp node_exporter.service /etc/systemd/system
  systemctl daemon-reload
  systemctl enable node_exporter --now 

  return
}

[ -f /etc/systemd/system/node_exporter.service ]
  if [[ ! $? -eq 0 ]]; then
    install_exporter
    else
      echo -en "\033[93m\n It seems that node_exporter is already installed \033[0m\n\n";
    exit 1
  fi

sleep 3

wget -O - http://localhost:9100 | grep "Prometheus Node Exporter" &> /dev/null
if [ $? -eq 0 ]; then
  echo -en "\033[92m\n Node_exporter successfully installed and working on 9100 port \033[0m\n\n"
  elif [ ! $? -eq 0 ]; then
    echo -en "\033[91m\n Node_exporter page in now available, check if port 9100 is not open  \033[0m\n\n"
fi
